const conjuntoEntrenamiento2 = [
    {
        "hair": 1,
        "feathers": 0,
        "eggs": 0,
        "milk": 1,
        "airborne": 0,
        "aquatic": 0,
        "predator": 1,
        "teeth": 1,
        "backbone": 1,
        "breathes": 1,
        "venemous": 0,
        "fins": 0,
        "legs": 4,
        "tails": 0,
        "domestic": 0,
        "catsize": 1,
        "classification_of_animal": 1
    },
    {
        "hair": 1,
        "feathers": 0,
        "eggs": 0,
        "milk": 1,
        "airborne": 0,
        "aquatic": 0,
        "predator": 0,
        "teeth": 1,
        "backbone": 1,
        "breathes": 1,
        "venemous": 0,
        "fins": 0,
        "legs": 4,
        "tails": 1,
        "domestic": 0,
        "catsize": 1,
        "classification_of_animal": 1
    },
    {
        "hair": 0,
        "feathers": 0,
        "eggs": 1,
        "milk": 0,
        "airborne": 0,
        "aquatic": 1,
        "predator": 1,
        "teeth": 1,
        "backbone": 1,
        "breathes": 0,
        "venemous": 0,
        "fins": 1,
        "legs": 0,
        "tails": 1,
        "domestic": 0,
        "catsize": 0,
        "classification_of_animal": 4
    },
    {
        "hair": 1,
        "feathers": 0,
        "eggs": 0,
        "milk": 1,
        "airborne": 0,
        "aquatic": 0,
        "predator": 1,
        "teeth": 1,
        "backbone": 1,
        "breathes": 1,
        "venemous": 0,
        "fins": 0,
        "legs": 4,
        "tails": 0,
        "domestic": 0,
        "catsize": 1,
        "classification_of_animal": 1
    },
    {
        "hair": 1,
        "feathers": 0,
        "eggs": 0,
        "milk": 1,
        "airborne": 0,
        "aquatic": 0,
        "predator": 1,
        "teeth": 1,
        "backbone": 1,
        "breathes": 1,
        "venemous": 0,
        "fins": 0,
        "legs": 4,
        "tails": 1,
        "domestic": 0,
        "catsize": 1,
        "classification_of_animal": 1
    },
    {
        "hair": 1,
        "feathers": 0,
        "eggs": 0,
        "milk": 1,
        "airborne": 0,
        "aquatic": 0,
        "predator": 0,
        "teeth": 1,
        "backbone": 1,
        "breathes": 1,
        "venemous": 0,
        "fins": 0,
        "legs": 4,
        "tails": 1,
        "domestic": 0,
        "catsize": 1,
        "classification_of_animal": 1
    },
    {
        "hair": 1,
        "feathers": 0,
        "eggs": 0,
        "milk": 1,
        "airborne": 0,
        "aquatic": 0,
        "predator": 0,
        "teeth": 1,
        "backbone": 1,
        "breathes": 1,
        "venemous": 0,
        "fins": 0,
        "legs": 4,
        "tails": 1,
        "domestic": 1,
        "catsize": 1,
        "classification_of_animal": 1
    },
    {
        "hair": 0,
        "feathers": 0,
        "eggs": 1,
        "milk": 0,
        "airborne": 0,
        "aquatic": 1,
        "predator": 0,
        "teeth": 1,
        "backbone": 1,
        "breathes": 0,
        "venemous": 0,
        "fins": 1,
        "legs": 0,
        "tails": 1,
        "domestic": 1,
        "catsize": 0,
        "classification_of_animal": 4
    },
    {
        "hair": 0,
        "feathers": 0,
        "eggs": 1,
        "milk": 0,
        "airborne": 0,
        "aquatic": 1,
        "predator": 1,
        "teeth": 1,
        "backbone": 1,
        "breathes": 0,
        "venemous": 0,
        "fins": 1,
        "legs": 0,
        "tails": 1,
        "domestic": 0,
        "catsize": 0,
        "classification_of_animal": 4
    },
    {
        "hair": 1,
        "feathers": 0,
        "eggs": 0,
        "milk": 1,
        "airborne": 0,
        "aquatic": 0,
        "predator": 0,
        "teeth": 1,
        "backbone": 1,
        "breathes": 1,
        "venemous": 0,
        "fins": 0,
        "legs": 4,
        "tails": 0,
        "domestic": 1,
        "catsize": 0,
        "classification_of_animal": 1
    },
    {
        "hair": 1,
        "feathers": 0,
        "eggs": 0,
        "milk": 1,
        "airborne": 0,
        "aquatic": 0,
        "predator": 1,
        "teeth": 1,
        "backbone": 1,
        "breathes": 1,
        "venemous": 0,
        "fins": 0,
        "legs": 4,
        "tails": 1,
        "domestic": 0,
        "catsize": 1,
        "classification_of_animal": 1
    },
    {
        "hair": 0,
        "feathers": 1,
        "eggs": 1,
        "milk": 0,
        "airborne": 1,
        "aquatic": 0,
        "predator": 0,
        "teeth": 0,
        "backbone": 1,
        "breathes": 1,
        "venemous": 0,
        "fins": 0,
        "legs": 2,
        "tails": 1,
        "domestic": 1,
        "catsize": 0,
        "classification_of_animal": 2
    },
    {
        "hair": 0,
        "feathers": 0,
        "eggs": 1,
        "milk": 0,
        "airborne": 0,
        "aquatic": 1,
        "predator": 1,
        "teeth": 1,
        "backbone": 1,
        "breathes": 0,
        "venemous": 0,
        "fins": 1,
        "legs": 0,
        "tails": 1,
        "domestic": 0,
        "catsize": 0,
        "classification_of_animal": 4
    },
    {
        "hair": 0,
        "feathers": 0,
        "eggs": 1,
        "milk": 0,
        "airborne": 0,
        "aquatic": 0,
        "predator": 1,
        "teeth": 0,
        "backbone": 0,
        "breathes": 0,
        "venemous": 0,
        "fins": 0,
        "legs": 0,
        "tails": 0,
        "domestic": 0,
        "catsize": 0,
        "classification_of_animal": 7
    },
    {
        "hair": 0,
        "feathers": 0,
        "eggs": 1,
        "milk": 0,
        "airborne": 0,
        "aquatic": 1,
        "predator": 1,
        "teeth": 0,
        "backbone": 0,
        "breathes": 0,
        "venemous": 0,
        "fins": 0,
        "legs": 4,
        "tails": 0,
        "domestic": 0,
        "catsize": 0,
        "classification_of_animal": 7
    },
    {
        "hair": 0,
        "feathers": 0,
        "eggs": 1,
        "milk": 0,
        "airborne": 0,
        "aquatic": 1,
        "predator": 1,
        "teeth": 0,
        "backbone": 0,
        "breathes": 0,
        "venemous": 0,
        "fins": 0,
        "legs": 6,
        "tails": 0,
        "domestic": 0,
        "catsize": 0,
        "classification_of_animal": 7
    },
    {
        "hair": 0,
        "feathers": 1,
        "eggs": 1,
        "milk": 0,
        "airborne": 1,
        "aquatic": 0,
        "predator": 1,
        "teeth": 0,
        "backbone": 1,
        "breathes": 1,
        "venemous": 0,
        "fins": 0,
        "legs": 2,
        "tails": 1,
        "domestic": 0,
        "catsize": 0,
        "classification_of_animal": 2
    },
    {
        "hair": 1,
        "feathers": 0,
        "eggs": 0,
        "milk": 1,
        "airborne": 0,
        "aquatic": 0,
        "predator": 0,
        "teeth": 1,
        "backbone": 1,
        "breathes": 1,
        "venemous": 0,
        "fins": 0,
        "legs": 4,
        "tails": 1,
        "domestic": 0,
        "catsize": 1,
        "classification_of_animal": 1
    },
    {
        "hair": 0,
        "feathers": 0,
        "eggs": 1,
        "milk": 0,
        "airborne": 0,
        "aquatic": 1,
        "predator": 1,
        "teeth": 1,
        "backbone": 1,
        "breathes": 0,
        "venemous": 0,
        "fins": 1,
        "legs": 0,
        "tails": 1,
        "domestic": 0,
        "catsize": 1,
        "classification_of_animal": 4
    },
    {
        "hair": 0,
        "feathers": 0,
        "eggs": 0,
        "milk": 1,
        "airborne": 0,
        "aquatic": 1,
        "predator": 1,
        "teeth": 1,
        "backbone": 1,
        "breathes": 1,
        "venemous": 0,
        "fins": 1,
        "legs": 0,
        "tails": 1,
        "domestic": 0,
        "catsize": 1,
        "classification_of_animal": 1
    },
    {
        "hair": 0,
        "feathers": 1,
        "eggs": 1,
        "milk": 0,
        "airborne": 1,
        "aquatic": 0,
        "predator": 0,
        "teeth": 0,
        "backbone": 1,
        "breathes": 1,
        "venemous": 0,
        "fins": 0,
        "legs": 2,
        "tails": 1,
        "domestic": 1,
        "catsize": 0,
        "classification_of_animal": 2
    },
    {
        "hair": 0,
        "feathers": 1,
        "eggs": 1,
        "milk": 0,
        "airborne": 1,
        "aquatic": 1,
        "predator": 0,
        "teeth": 0,
        "backbone": 1,
        "breathes": 1,
        "venemous": 0,
        "fins": 0,
        "legs": 2,
        "tails": 1,
        "domestic": 0,
        "catsize": 0,
        "classification_of_animal": 2
    },
    {
        "hair": 1,
        "feathers": 0,
        "eggs": 0,
        "milk": 1,
        "airborne": 0,
        "aquatic": 0,
        "predator": 0,
        "teeth": 1,
        "backbone": 1,
        "breathes": 1,
        "venemous": 0,
        "fins": 0,
        "legs": 4,
        "tails": 1,
        "domestic": 0,
        "catsize": 1,
        "classification_of_animal": 1
    },
    {
        "hair": 0,
        "feathers": 1,
        "eggs": 1,
        "milk": 0,
        "airborne": 1,
        "aquatic": 0,
        "predator": 0,
        "teeth": 0,
        "backbone": 1,
        "breathes": 1,
        "venemous": 0,
        "fins": 0,
        "legs": 2,
        "tails": 1,
        "domestic": 0,
        "catsize": 1,
        "classification_of_animal": 2
    },
    {
        "hair": 0,
        "feathers": 0,
        "eggs": 1,
        "milk": 0,
        "airborne": 0,
        "aquatic": 0,
        "predator": 0,
        "teeth": 0,
        "backbone": 0,
        "breathes": 1,
        "venemous": 0,
        "fins": 0,
        "legs": 6,
        "tails": 0,
        "domestic": 0,
        "catsize": 0,
        "classification_of_animal": 6
    },
    {
        "hair": 0,
        "feathers": 0,
        "eggs": 1,
        "milk": 0,
        "airborne": 0,
        "aquatic": 1,
        "predator": 1,
        "teeth": 1,
        "backbone": 1,
        "breathes": 1,
        "venemous": 0,
        "fins": 0,
        "legs": 4,
        "tails": 0,
        "domestic": 0,
        "catsize": 0,
        "classification_of_animal": 5
    },
    {
        "hair": 0,
        "feathers": 0,
        "eggs": 1,
        "milk": 0,
        "airborne": 0,
        "aquatic": 1,
        "predator": 1,
        "teeth": 1,
        "backbone": 1,
        "breathes": 1,
        "venemous": 1,
        "fins": 0,
        "legs": 4,
        "tails": 0,
        "domestic": 0,
        "catsize": 0,
        "classification_of_animal": 5
    },
    {
        "hair": 1,
        "feathers": 0,
        "eggs": 0,
        "milk": 1,
        "airborne": 1,
        "aquatic": 0,
        "predator": 0,
        "teeth": 1,
        "backbone": 1,
        "breathes": 1,
        "venemous": 0,
        "fins": 0,
        "legs": 2,
        "tails": 1,
        "domestic": 0,
        "catsize": 0,
        "classification_of_animal": 1
    },
    {
        "hair": 1,
        "feathers": 0,
        "eggs": 0,
        "milk": 1,
        "airborne": 0,
        "aquatic": 0,
        "predator": 0,
        "teeth": 1,
        "backbone": 1,
        "breathes": 1,
        "venemous": 0,
        "fins": 0,
        "legs": 4,
        "tails": 1,
        "domestic": 0,
        "catsize": 1,
        "classification_of_animal": 1
    },
    {
        "hair": 1,
        "feathers": 0,
        "eggs": 0,
        "milk": 1,
        "airborne": 0,
        "aquatic": 0,
        "predator": 1,
        "teeth": 1,
        "backbone": 1,
        "breathes": 1,
        "venemous": 0,
        "fins": 0,
        "legs": 2,
        "tails": 0,
        "domestic": 1,
        "catsize": 1,
        "classification_of_animal": 1
    },
    {
        "hair": 0,
        "feathers": 0,
        "eggs": 1,
        "milk": 0,
        "airborne": 1,
        "aquatic": 0,
        "predator": 0,
        "teeth": 0,
        "backbone": 0,
        "breathes": 1,
        "venemous": 0,
        "fins": 0,
        "legs": 6,
        "tails": 0,
        "domestic": 0,
        "catsize": 0,
        "classification_of_animal": 6
    },
    {
        "hair": 1,
        "feathers": 0,
        "eggs": 0,
        "milk": 1,
        "airborne": 0,
        "aquatic": 0,
        "predator": 0,
        "teeth": 1,
        "backbone": 1,
        "breathes": 1,
        "venemous": 0,
        "fins": 0,
        "legs": 4,
        "tails": 1,
        "domestic": 1,
        "catsize": 1,
        "classification_of_animal": 1
    },
    {
        "hair": 1,
        "feathers": 0,
        "eggs": 0,
        "milk": 1,
        "airborne": 0,
        "aquatic": 0,
        "predator": 0,
        "teeth": 1,
        "backbone": 1,
        "breathes": 1,
        "venemous": 0,
        "fins": 0,
        "legs": 2,
        "tails": 0,
        "domestic": 0,
        "catsize": 1,
        "classification_of_animal": 1
    },
    {
        "hair": 0,
        "feathers": 1,
        "eggs": 1,
        "milk": 0,
        "airborne": 1,
        "aquatic": 1,
        "predator": 1,
        "teeth": 0,
        "backbone": 1,
        "breathes": 1,
        "venemous": 0,
        "fins": 0,
        "legs": 2,
        "tails": 1,
        "domestic": 0,
        "catsize": 0,
        "classification_of_animal": 2
    },
    {
        "hair": 0,
        "feathers": 0,
        "eggs": 1,
        "milk": 0,
        "airborne": 0,
        "aquatic": 1,
        "predator": 0,
        "teeth": 1,
        "backbone": 1,
        "breathes": 0,
        "venemous": 0,
        "fins": 1,
        "legs": 0,
        "tails": 1,
        "domestic": 0,
        "catsize": 0,
        "classification_of_animal": 4
    },
    {
        "hair": 1,
        "feathers": 0,
        "eggs": 0,
        "milk": 1,
        "airborne": 0,
        "aquatic": 0,
        "predator": 0,
        "teeth": 1,
        "backbone": 1,
        "breathes": 1,
        "venemous": 0,
        "fins": 0,
        "legs": 4,
        "tails": 1,
        "domestic": 1,
        "catsize": 0,
        "classification_of_animal": 1
    },
    {
        "hair": 1,
        "feathers": 0,
        "eggs": 0,
        "milk": 1,
        "airborne": 0,
        "aquatic": 0,
        "predator": 0,
        "teeth": 1,
        "backbone": 1,
        "breathes": 1,
        "venemous": 0,
        "fins": 0,
        "legs": 4,
        "tails": 1,
        "domestic": 0,
        "catsize": 0,
        "classification_of_animal": 1
    },
    {
        "hair": 0,
        "feathers": 1,
        "eggs": 1,
        "milk": 0,
        "airborne": 1,
        "aquatic": 0,
        "predator": 1,
        "teeth": 0,
        "backbone": 1,
        "breathes": 1,
        "venemous": 0,
        "fins": 0,
        "legs": 2,
        "tails": 1,
        "domestic": 0,
        "catsize": 0,
        "classification_of_animal": 2
    },
    {
        "hair": 0,
        "feathers": 0,
        "eggs": 1,
        "milk": 0,
        "airborne": 0,
        "aquatic": 1,
        "predator": 1,
        "teeth": 1,
        "backbone": 1,
        "breathes": 0,
        "venemous": 0,
        "fins": 1,
        "legs": 0,
        "tails": 1,
        "domestic": 0,
        "catsize": 0,
        "classification_of_animal": 4
    },
    {
        "hair": 1,
        "feathers": 0,
        "eggs": 1,
        "milk": 0,
        "airborne": 1,
        "aquatic": 0,
        "predator": 0,
        "teeth": 0,
        "backbone": 0,
        "breathes": 1,
        "venemous": 1,
        "fins": 0,
        "legs": 6,
        "tails": 0,
        "domestic": 1,
        "catsize": 0,
        "classification_of_animal": 6
    },
    {
        "hair": 1,
        "feathers": 0,
        "eggs": 1,
        "milk": 0,
        "airborne": 1,
        "aquatic": 0,
        "predator": 0,
        "teeth": 0,
        "backbone": 0,
        "breathes": 1,
        "venemous": 0,
        "fins": 0,
        "legs": 6,
        "tails": 0,
        "domestic": 0,
        "catsize": 0,
        "classification_of_animal": 6
    },
    {
        "hair": 0,
        "feathers": 1,
        "eggs": 1,
        "milk": 0,
        "airborne": 0,
        "aquatic": 0,
        "predator": 1,
        "teeth": 0,
        "backbone": 1,
        "breathes": 1,
        "venemous": 0,
        "fins": 0,
        "legs": 2,
        "tails": 1,
        "domestic": 0,
        "catsize": 0,
        "classification_of_animal": 2
    },
    {
        "hair": 0,
        "feathers": 0,
        "eggs": 1,
        "milk": 0,
        "airborne": 1,
        "aquatic": 0,
        "predator": 1,
        "teeth": 0,
        "backbone": 0,
        "breathes": 1,
        "venemous": 0,
        "fins": 0,
        "legs": 6,
        "tails": 0,
        "domestic": 0,
        "catsize": 0,
        "classification_of_animal": 6
    },
    {
        "hair": 0,
        "feathers": 1,
        "eggs": 1,
        "milk": 0,
        "airborne": 1,
        "aquatic": 0,
        "predator": 0,
        "teeth": 0,
        "backbone": 1,
        "breathes": 1,
        "venemous": 0,
        "fins": 0,
        "legs": 2,
        "tails": 1,
        "domestic": 0,
        "catsize": 0,
        "classification_of_animal": 2
    },
    {
        "hair": 1,
        "feathers": 0,
        "eggs": 0,
        "milk": 1,
        "airborne": 0,
        "aquatic": 0,
        "predator": 1,
        "teeth": 1,
        "backbone": 1,
        "breathes": 1,
        "venemous": 0,
        "fins": 0,
        "legs": 4,
        "tails": 1,
        "domestic": 0,
        "catsize": 1,
        "classification_of_animal": 1
    },
    {
        "hair": 1,
        "feathers": 0,
        "eggs": 0,
        "milk": 1,
        "airborne": 0,
        "aquatic": 0,
        "predator": 1,
        "teeth": 1,
        "backbone": 1,
        "breathes": 1,
        "venemous": 0,
        "fins": 0,
        "legs": 4,
        "tails": 1,
        "domestic": 0,
        "catsize": 1,
        "classification_of_animal": 1
    },
    {
        "hair": 0,
        "feathers": 0,
        "eggs": 1,
        "milk": 0,
        "airborne": 0,
        "aquatic": 1,
        "predator": 1,
        "teeth": 0,
        "backbone": 0,
        "breathes": 0,
        "venemous": 0,
        "fins": 0,
        "legs": 6,
        "tails": 0,
        "domestic": 0,
        "catsize": 0,
        "classification_of_animal": 7
    },
    {
        "hair": 1,
        "feathers": 0,
        "eggs": 0,
        "milk": 1,
        "airborne": 0,
        "aquatic": 0,
        "predator": 1,
        "teeth": 1,
        "backbone": 1,
        "breathes": 1,
        "venemous": 0,
        "fins": 0,
        "legs": 4,
        "tails": 1,
        "domestic": 0,
        "catsize": 1,
        "classification_of_animal": 1
    },
    {
        "hair": 1,
        "feathers": 0,
        "eggs": 0,
        "milk": 1,
        "airborne": 0,
        "aquatic": 1,
        "predator": 1,
        "teeth": 1,
        "backbone": 1,
        "breathes": 1,
        "venemous": 0,
        "fins": 0,
        "legs": 4,
        "tails": 1,
        "domestic": 0,
        "catsize": 1,
        "classification_of_animal": 1
    },
    {
        "hair": 1,
        "feathers": 0,
        "eggs": 0,
        "milk": 1,
        "airborne": 0,
        "aquatic": 0,
        "predator": 1,
        "teeth": 1,
        "backbone": 1,
        "breathes": 1,
        "venemous": 0,
        "fins": 0,
        "legs": 4,
        "tails": 1,
        "domestic": 0,
        "catsize": 0,
        "classification_of_animal": 1
    },
    {
        "hair": 1,
        "feathers": 0,
        "eggs": 0,
        "milk": 1,
        "airborne": 0,
        "aquatic": 0,
        "predator": 1,
        "teeth": 1,
        "backbone": 1,
        "breathes": 1,
        "venemous": 0,
        "fins": 0,
        "legs": 4,
        "tails": 1,
        "domestic": 0,
        "catsize": 1,
        "classification_of_animal": 1
    },
    {
        "hair": 1,
        "feathers": 0,
        "eggs": 1,
        "milk": 0,
        "airborne": 1,
        "aquatic": 0,
        "predator": 0,
        "teeth": 0,
        "backbone": 0,
        "breathes": 1,
        "venemous": 0,
        "fins": 0,
        "legs": 6,
        "tails": 0,
        "domestic": 0,
        "catsize": 0,
        "classification_of_animal": 6
    },
    {
        "hair": 0,
        "feathers": 0,
        "eggs": 1,
        "milk": 0,
        "airborne": 0,
        "aquatic": 1,
        "predator": 1,
        "teeth": 1,
        "backbone": 1,
        "breathes": 1,
        "venemous": 0,
        "fins": 0,
        "legs": 4,
        "tails": 1,
        "domestic": 0,
        "catsize": 0,
        "classification_of_animal": 5
    },
    {
        "hair": 0,
        "feathers": 0,
        "eggs": 1,
        "milk": 0,
        "airborne": 0,
        "aquatic": 1,
        "predator": 1,
        "teeth": 0,
        "backbone": 0,
        "breathes": 0,
        "venemous": 0,
        "fins": 0,
        "legs": 8,
        "tails": 0,
        "domestic": 0,
        "catsize": 1,
        "classification_of_animal": 7
    },
    {
        "hair": 1,
        "feathers": 0,
        "eggs": 0,
        "milk": 1,
        "airborne": 0,
        "aquatic": 0,
        "predator": 1,
        "teeth": 1,
        "backbone": 1,
        "breathes": 1,
        "venemous": 0,
        "fins": 0,
        "legs": 4,
        "tails": 1,
        "domestic": 0,
        "catsize": 0,
        "classification_of_animal": 1
    },
    {
        "hair": 1,
        "feathers": 0,
        "eggs": 0,
        "milk": 1,
        "airborne": 0,
        "aquatic": 0,
        "predator": 0,
        "teeth": 1,
        "backbone": 1,
        "breathes": 1,
        "venemous": 0,
        "fins": 0,
        "legs": 4,
        "tails": 1,
        "domestic": 0,
        "catsize": 1,
        "classification_of_animal": 1
    },
    {
        "hair": 0,
        "feathers": 1,
        "eggs": 1,
        "milk": 0,
        "airborne": 0,
        "aquatic": 0,
        "predator": 0,
        "teeth": 0,
        "backbone": 1,
        "breathes": 1,
        "venemous": 0,
        "fins": 0,
        "legs": 2,
        "tails": 1,
        "domestic": 0,
        "catsize": 1,
        "classification_of_animal": 2
    },
    {
        "hair": 0,
        "feathers": 1,
        "eggs": 1,
        "milk": 0,
        "airborne": 1,
        "aquatic": 0,
        "predator": 0,
        "teeth": 0,
        "backbone": 1,
        "breathes": 1,
        "venemous": 0,
        "fins": 0,
        "legs": 2,
        "tails": 1,
        "domestic": 1,
        "catsize": 0,
        "classification_of_animal": 2
    },
    {
        "hair": 0,
        "feathers": 1,
        "eggs": 1,
        "milk": 0,
        "airborne": 0,
        "aquatic": 1,
        "predator": 1,
        "teeth": 0,
        "backbone": 1,
        "breathes": 1,
        "venemous": 0,
        "fins": 0,
        "legs": 2,
        "tails": 1,
        "domestic": 0,
        "catsize": 1,
        "classification_of_animal": 2
    },
    {
        "hair": 0,
        "feathers": 1,
        "eggs": 1,
        "milk": 0,
        "airborne": 1,
        "aquatic": 0,
        "predator": 0,
        "teeth": 0,
        "backbone": 1,
        "breathes": 1,
        "venemous": 0,
        "fins": 0,
        "legs": 2,
        "tails": 1,
        "domestic": 0,
        "catsize": 0,
        "classification_of_animal": 2
    },
    {
        "hair": 0,
        "feathers": 0,
        "eggs": 1,
        "milk": 0,
        "airborne": 0,
        "aquatic": 1,
        "predator": 1,
        "teeth": 1,
        "backbone": 1,
        "breathes": 0,
        "venemous": 0,
        "fins": 1,
        "legs": 0,
        "tails": 1,
        "domestic": 0,
        "catsize": 1,
        "classification_of_animal": 4
    },
    {
        "hair": 0,
        "feathers": 0,
        "eggs": 1,
        "milk": 0,
        "airborne": 0,
        "aquatic": 1,
        "predator": 1,
        "teeth": 1,
        "backbone": 1,
        "breathes": 0,
        "venemous": 0,
        "fins": 1,
        "legs": 0,
        "tails": 1,
        "domestic": 0,
        "catsize": 0,
        "classification_of_animal": 4
    },
    {
        "hair": 0,
        "feathers": 0,
        "eggs": 1,
        "milk": 0,
        "airborne": 0,
        "aquatic": 0,
        "predator": 1,
        "teeth": 1,
        "backbone": 1,
        "breathes": 1,
        "venemous": 1,
        "fins": 0,
        "legs": 0,
        "tails": 1,
        "domestic": 0,
        "catsize": 0,
        "classification_of_animal": 3
    },
    {
        "hair": 1,
        "feathers": 0,
        "eggs": 1,
        "milk": 1,
        "airborne": 0,
        "aquatic": 1,
        "predator": 1,
        "teeth": 0,
        "backbone": 1,
        "breathes": 1,
        "venemous": 0,
        "fins": 0,
        "legs": 4,
        "tails": 1,
        "domestic": 0,
        "catsize": 1,
        "classification_of_animal": 1
    },
    {
        "hair": 1,
        "feathers": 0,
        "eggs": 0,
        "milk": 1,
        "airborne": 0,
        "aquatic": 0,
        "predator": 1,
        "teeth": 1,
        "backbone": 1,
        "breathes": 1,
        "venemous": 0,
        "fins": 0,
        "legs": 4,
        "tails": 1,
        "domestic": 0,
        "catsize": 1,
        "classification_of_animal": 1
    },
    {
        "hair": 1,
        "feathers": 0,
        "eggs": 0,
        "milk": 1,
        "airborne": 0,
        "aquatic": 0,
        "predator": 0,
        "teeth": 1,
        "backbone": 1,
        "breathes": 1,
        "venemous": 0,
        "fins": 0,
        "legs": 4,
        "tails": 1,
        "domestic": 1,
        "catsize": 1,
        "classification_of_animal": 1
    },
    {
        "hair": 0,
        "feathers": 0,
        "eggs": 0,
        "milk": 1,
        "airborne": 0,
        "aquatic": 1,
        "predator": 1,
        "teeth": 1,
        "backbone": 1,
        "breathes": 1,
        "venemous": 0,
        "fins": 1,
        "legs": 0,
        "tails": 1,
        "domestic": 0,
        "catsize": 1,
        "classification_of_animal": 1
    },
    {
        "hair": 1,
        "feathers": 0,
        "eggs": 0,
        "milk": 1,
        "airborne": 0,
        "aquatic": 0,
        "predator": 1,
        "teeth": 1,
        "backbone": 1,
        "breathes": 1,
        "venemous": 0,
        "fins": 0,
        "legs": 4,
        "tails": 1,
        "domestic": 0,
        "catsize": 1,
        "classification_of_animal": 1
    },
    {
        "hair": 1,
        "feathers": 0,
        "eggs": 0,
        "milk": 1,
        "airborne": 0,
        "aquatic": 0,
        "predator": 1,
        "teeth": 1,
        "backbone": 1,
        "breathes": 1,
        "venemous": 0,
        "fins": 0,
        "legs": 4,
        "tails": 1,
        "domestic": 1,
        "catsize": 1,
        "classification_of_animal": 1
    },
    {
        "hair": 1,
        "feathers": 0,
        "eggs": 0,
        "milk": 1,
        "airborne": 0,
        "aquatic": 0,
        "predator": 1,
        "teeth": 1,
        "backbone": 1,
        "breathes": 1,
        "venemous": 0,
        "fins": 0,
        "legs": 4,
        "tails": 1,
        "domestic": 0,
        "catsize": 1,
        "classification_of_animal": 1
    },
    {
        "hair": 1,
        "feathers": 0,
        "eggs": 0,
        "milk": 1,
        "airborne": 0,
        "aquatic": 0,
        "predator": 0,
        "teeth": 1,
        "backbone": 1,
        "breathes": 1,
        "venemous": 0,
        "fins": 0,
        "legs": 4,
        "tails": 1,
        "domestic": 1,
        "catsize": 1,
        "classification_of_animal": 1
    },
    {
        "hair": 0,
        "feathers": 1,
        "eggs": 1,
        "milk": 0,
        "airborne": 0,
        "aquatic": 0,
        "predator": 1,
        "teeth": 0,
        "backbone": 1,
        "breathes": 1,
        "venemous": 0,
        "fins": 0,
        "legs": 2,
        "tails": 1,
        "domestic": 0,
        "catsize": 1,
        "classification_of_animal": 2
    },
    {
        "hair": 0,
        "feathers": 0,
        "eggs": 0,
        "milk": 0,
        "airborne": 0,
        "aquatic": 0,
        "predator": 1,
        "teeth": 0,
        "backbone": 0,
        "breathes": 1,
        "venemous": 1,
        "fins": 0,
        "legs": 8,
        "tails": 1,
        "domestic": 0,
        "catsize": 0,
        "classification_of_animal": 7
    },
    {
        "hair": 0,
        "feathers": 0,
        "eggs": 1,
        "milk": 0,
        "airborne": 0,
        "aquatic": 1,
        "predator": 0,
        "teeth": 1,
        "backbone": 1,
        "breathes": 0,
        "venemous": 0,
        "fins": 1,
        "legs": 0,
        "tails": 1,
        "domestic": 0,
        "catsize": 0,
        "classification_of_animal": 4
    },
    {
        "hair": 1,
        "feathers": 0,
        "eggs": 0,
        "milk": 1,
        "airborne": 0,
        "aquatic": 1,
        "predator": 1,
        "teeth": 1,
        "backbone": 1,
        "breathes": 1,
        "venemous": 0,
        "fins": 1,
        "legs": 0,
        "tails": 0,
        "domestic": 0,
        "catsize": 1,
        "classification_of_animal": 1
    },
    {
        "hair": 1,
        "feathers": 0,
        "eggs": 0,
        "milk": 1,
        "airborne": 0,
        "aquatic": 1,
        "predator": 1,
        "teeth": 1,
        "backbone": 1,
        "breathes": 1,
        "venemous": 0,
        "fins": 1,
        "legs": 2,
        "tails": 1,
        "domestic": 0,
        "catsize": 1,
        "classification_of_animal": 1
    },
    {
        "hair": 0,
        "feathers": 0,
        "eggs": 0,
        "milk": 0,
        "airborne": 0,
        "aquatic": 1,
        "predator": 1,
        "teeth": 1,
        "backbone": 1,
        "breathes": 0,
        "venemous": 1,
        "fins": 0,
        "legs": 0,
        "tails": 1,
        "domestic": 0,
        "catsize": 0,
        "classification_of_animal": 3
    },
    {
        "hair": 0,
        "feathers": 0,
        "eggs": 1,
        "milk": 0,
        "airborne": 0,
        "aquatic": 1,
        "predator": 1,
        "teeth": 0,
        "backbone": 0,
        "breathes": 0,
        "venemous": 1,
        "fins": 0,
        "legs": 0,
        "tails": 0,
        "domestic": 0,
        "catsize": 0,
        "classification_of_animal": 7
    },
    {
        "hair": 0,
        "feathers": 1,
        "eggs": 1,
        "milk": 0,
        "airborne": 1,
        "aquatic": 1,
        "predator": 1,
        "teeth": 0,
        "backbone": 1,
        "breathes": 1,
        "venemous": 0,
        "fins": 0,
        "legs": 2,
        "tails": 1,
        "domestic": 0,
        "catsize": 0,
        "classification_of_animal": 2
    },
    {
        "hair": 0,
        "feathers": 1,
        "eggs": 1,
        "milk": 0,
        "airborne": 1,
        "aquatic": 1,
        "predator": 1,
        "teeth": 0,
        "backbone": 1,
        "breathes": 1,
        "venemous": 0,
        "fins": 0,
        "legs": 2,
        "tails": 1,
        "domestic": 0,
        "catsize": 0,
        "classification_of_animal": 2
    },
    {
        "hair": 0,
        "feathers": 0,
        "eggs": 1,
        "milk": 0,
        "airborne": 0,
        "aquatic": 0,
        "predator": 1,
        "teeth": 1,
        "backbone": 1,
        "breathes": 1,
        "venemous": 0,
        "fins": 0,
        "legs": 0,
        "tails": 1,
        "domestic": 0,
        "catsize": 0,
        "classification_of_animal": 3
    },
    {
        "hair": 0,
        "feathers": 0,
        "eggs": 1,
        "milk": 0,
        "airborne": 0,
        "aquatic": 0,
        "predator": 0,
        "teeth": 0,
        "backbone": 0,
        "breathes": 1,
        "venemous": 0,
        "fins": 0,
        "legs": 0,
        "tails": 0,
        "domestic": 0,
        "catsize": 0,
        "classification_of_animal": 7
    },
    {
        "hair": 0,
        "feathers": 0,
        "eggs": 1,
        "milk": 0,
        "airborne": 0,
        "aquatic": 1,
        "predator": 0,
        "teeth": 1,
        "backbone": 1,
        "breathes": 0,
        "venemous": 0,
        "fins": 1,
        "legs": 0,
        "tails": 1,
        "domestic": 0,
        "catsize": 0,
        "classification_of_animal": 4
    },
    {
        "hair": 0,
        "feathers": 1,
        "eggs": 1,
        "milk": 0,
        "airborne": 1,
        "aquatic": 0,
        "predator": 0,
        "teeth": 0,
        "backbone": 1,
        "breathes": 1,
        "venemous": 0,
        "fins": 0,
        "legs": 2,
        "tails": 1,
        "domestic": 0,
        "catsize": 0,
        "classification_of_animal": 2
    },
    {
        "hair": 1,
        "feathers": 0,
        "eggs": 0,
        "milk": 1,
        "airborne": 0,
        "aquatic": 0,
        "predator": 0,
        "teeth": 1,
        "backbone": 1,
        "breathes": 1,
        "venemous": 0,
        "fins": 0,
        "legs": 2,
        "tails": 1,
        "domestic": 0,
        "catsize": 0,
        "classification_of_animal": 1
    },
    {
        "hair": 0,
        "feathers": 0,
        "eggs": 1,
        "milk": 0,
        "airborne": 0,
        "aquatic": 1,
        "predator": 1,
        "teeth": 0,
        "backbone": 0,
        "breathes": 0,
        "venemous": 0,
        "fins": 0,
        "legs": 5,
        "tails": 0,
        "domestic": 0,
        "catsize": 0,
        "classification_of_animal": 7
    },
    {
        "hair": 0,
        "feathers": 0,
        "eggs": 1,
        "milk": 0,
        "airborne": 0,
        "aquatic": 1,
        "predator": 1,
        "teeth": 1,
        "backbone": 1,
        "breathes": 0,
        "venemous": 1,
        "fins": 1,
        "legs": 0,
        "tails": 1,
        "domestic": 0,
        "catsize": 1,
        "classification_of_animal": 4
    },
    {
        "hair": 0,
        "feathers": 1,
        "eggs": 1,
        "milk": 0,
        "airborne": 1,
        "aquatic": 1,
        "predator": 0,
        "teeth": 0,
        "backbone": 1,
        "breathes": 1,
        "venemous": 0,
        "fins": 0,
        "legs": 2,
        "tails": 1,
        "domestic": 0,
        "catsize": 1,
        "classification_of_animal": 2
    },
    {
        "hair": 0,
        "feathers": 0,
        "eggs": 1,
        "milk": 0,
        "airborne": 0,
        "aquatic": 0,
        "predator": 0,
        "teeth": 0,
        "backbone": 0,
        "breathes": 1,
        "venemous": 0,
        "fins": 0,
        "legs": 6,
        "tails": 0,
        "domestic": 0,
        "catsize": 0,
        "classification_of_animal": 6
    },
    {
        "hair": 0,
        "feathers": 0,
        "eggs": 1,
        "milk": 0,
        "airborne": 0,
        "aquatic": 1,
        "predator": 0,
        "teeth": 1,
        "backbone": 1,
        "breathes": 1,
        "venemous": 0,
        "fins": 0,
        "legs": 4,
        "tails": 0,
        "domestic": 0,
        "catsize": 0,
        "classification_of_animal": 5
    },
    {
        "hair": 0,
        "feathers": 0,
        "eggs": 1,
        "milk": 0,
        "airborne": 0,
        "aquatic": 0,
        "predator": 0,
        "teeth": 0,
        "backbone": 1,
        "breathes": 1,
        "venemous": 0,
        "fins": 0,
        "legs": 4,
        "tails": 1,
        "domestic": 0,
        "catsize": 1,
        "classification_of_animal": 3
    },
    {
        "hair": 0,
        "feathers": 0,
        "eggs": 1,
        "milk": 0,
        "airborne": 0,
        "aquatic": 0,
        "predator": 1,
        "teeth": 1,
        "backbone": 1,
        "breathes": 1,
        "venemous": 0,
        "fins": 0,
        "legs": 4,
        "tails": 1,
        "domestic": 0,
        "catsize": 0,
        "classification_of_animal": 3
    },
    {
        "hair": 0,
        "feathers": 0,
        "eggs": 1,
        "milk": 0,
        "airborne": 0,
        "aquatic": 1,
        "predator": 1,
        "teeth": 1,
        "backbone": 1,
        "breathes": 0,
        "venemous": 0,
        "fins": 1,
        "legs": 0,
        "tails": 1,
        "domestic": 0,
        "catsize": 1,
        "classification_of_animal": 4
    },
    {
        "hair": 1,
        "feathers": 0,
        "eggs": 0,
        "milk": 1,
        "airborne": 1,
        "aquatic": 0,
        "predator": 0,
        "teeth": 1,
        "backbone": 1,
        "breathes": 1,
        "venemous": 0,
        "fins": 0,
        "legs": 2,
        "tails": 1,
        "domestic": 0,
        "catsize": 0,
        "classification_of_animal": 1
    },
    {
        "hair": 1,
        "feathers": 0,
        "eggs": 0,
        "milk": 1,
        "airborne": 0,
        "aquatic": 0,
        "predator": 0,
        "teeth": 1,
        "backbone": 1,
        "breathes": 1,
        "venemous": 0,
        "fins": 0,
        "legs": 4,
        "tails": 1,
        "domestic": 0,
        "catsize": 0,
        "classification_of_animal": 1
    },
    {
        "hair": 0,
        "feathers": 1,
        "eggs": 1,
        "milk": 0,
        "airborne": 1,
        "aquatic": 0,
        "predator": 1,
        "teeth": 0,
        "backbone": 1,
        "breathes": 1,
        "venemous": 0,
        "fins": 0,
        "legs": 2,
        "tails": 1,
        "domestic": 0,
        "catsize": 1,
        "classification_of_animal": 2
    },
    {
        "hair": 1,
        "feathers": 0,
        "eggs": 0,
        "milk": 1,
        "airborne": 0,
        "aquatic": 0,
        "predator": 0,
        "teeth": 1,
        "backbone": 1,
        "breathes": 1,
        "venemous": 0,
        "fins": 0,
        "legs": 2,
        "tails": 1,
        "domestic": 0,
        "catsize": 1,
        "classification_of_animal": 1
    },
    {
        "hair": 1,
        "feathers": 0,
        "eggs": 1,
        "milk": 0,
        "airborne": 1,
        "aquatic": 0,
        "predator": 0,
        "teeth": 0,
        "backbone": 0,
        "breathes": 1,
        "venemous": 1,
        "fins": 0,
        "legs": 6,
        "tails": 0,
        "domestic": 0,
        "catsize": 0,
        "classification_of_animal": 6
    },
    {
        "hair": 1,
        "feathers": 0,
        "eggs": 0,
        "milk": 1,
        "airborne": 0,
        "aquatic": 0,
        "predator": 1,
        "teeth": 1,
        "backbone": 1,
        "breathes": 1,
        "venemous": 0,
        "fins": 0,
        "legs": 4,
        "tails": 1,
        "domestic": 0,
        "catsize": 1,
        "classification_of_animal": 1
    },
    {
        "hair": 0,
        "feathers": 0,
        "eggs": 1,
        "milk": 0,
        "airborne": 0,
        "aquatic": 0,
        "predator": 0,
        "teeth": 0,
        "backbone": 0,
        "breathes": 1,
        "venemous": 0,
        "fins": 0,
        "legs": 0,
        "tails": 0,
        "domestic": 0,
        "catsize": 0,
        "classification_of_animal": 7
    },
    {
        "hair": 0,
        "feathers": 1,
        "eggs": 1,
        "milk": 0,
        "airborne": 1,
        "aquatic": 0,
        "predator": 0,
        "teeth": 0,
        "backbone": 1,
        "breathes": 1,
        "venemous": 0,
        "fins": 0,
        "legs": 2,
        "tails": 1,
        "domestic": 0,
        "catsize": 0,
        "classification_of_animal": 2
    }
]

export default conjuntoEntrenamiento2;