const conjuntoEntrenamiento3 = [
    {
      "Hair": 1,
      "Feathers": 0,
      "Eggs": 0,
      "Milk": 1,
      "Airborne": 0,
      "Aquatic": 0,
      "Predator": 1,
      "Teeth": 1,
      "Backbone": 1,
      "Breathes": 1,
      "Venemous": 0,
      "Fins": 0,
      "Legs": 4,
      "Tails": 0,
      "Domestic": 0,
      "Catsize": 1,
      "Classification of Animal": 1
    },
    {
      "Hair": 1,
      "Feathers": 0,
      "Eggs": 0,
      "Milk": 1,
      "Airborne": 0,
      "Aquatic": 0,
      "Predator": 0,
      "Teeth": 1,
      "Backbone": 1,
      "Breathes": 1,
      "Venemous": 0,
      "Fins": 0,
      "Legs": 4,
      "Tails": 1,
      "Domestic": 0,
      "Catsize": 1,
      "Classification of Animal": 1
    },
    {
      "Hair": 0,
      "Feathers": 0,
      "Eggs": 1,
      "Milk": 0,
      "Airborne": 0,
      "Aquatic": 1,
      "Predator": 1,
      "Teeth": 1,
      "Backbone": 1,
      "Breathes": 0,
      "Venemous": 0,
      "Fins": 1,
      "Legs": 0,
      "Tails": 1,
      "Domestic": 0,
      "Catsize": 0,
      "Classification of Animal": 4
    },
    {
      "Hair": 1,
      "Feathers": 0,
      "Eggs": 0,
      "Milk": 1,
      "Airborne": 0,
      "Aquatic": 0,
      "Predator": 1,
      "Teeth": 1,
      "Backbone": 1,
      "Breathes": 1,
      "Venemous": 0,
      "Fins": 0,
      "Legs": 4,
      "Tails": 0,
      "Domestic": 0,
      "Catsize": 1,
      "Classification of Animal": 1
    },
    {
      "Hair": 1,
      "Feathers": 0,
      "Eggs": 0,
      "Milk": 1,
      "Airborne": 0,
      "Aquatic": 0,
      "Predator": 1,
      "Teeth": 1,
      "Backbone": 1,
      "Breathes": 1,
      "Venemous": 0,
      "Fins": 0,
      "Legs": 4,
      "Tails": 1,
      "Domestic": 0,
      "Catsize": 1,
      "Classification of Animal": 1
    },
    {
      "Hair": 1,
      "Feathers": 0,
      "Eggs": 0,
      "Milk": 1,
      "Airborne": 0,
      "Aquatic": 0,
      "Predator": 0,
      "Teeth": 1,
      "Backbone": 1,
      "Breathes": 1,
      "Venemous": 0,
      "Fins": 0,
      "Legs": 4,
      "Tails": 1,
      "Domestic": 0,
      "Catsize": 1,
      "Classification of Animal": 1
    },
    {
      "Hair": 1,
      "Feathers": 0,
      "Eggs": 0,
      "Milk": 1,
      "Airborne": 0,
      "Aquatic": 0,
      "Predator": 0,
      "Teeth": 1,
      "Backbone": 1,
      "Breathes": 1,
      "Venemous": 0,
      "Fins": 0,
      "Legs": 4,
      "Tails": 1,
      "Domestic": 1,
      "Catsize": 1,
      "Classification of Animal": 1
    },
    {
      "Hair": 0,
      "Feathers": 0,
      "Eggs": 1,
      "Milk": 0,
      "Airborne": 0,
      "Aquatic": 1,
      "Predator": 0,
      "Teeth": 1,
      "Backbone": 1,
      "Breathes": 0,
      "Venemous": 0,
      "Fins": 1,
      "Legs": 0,
      "Tails": 1,
      "Domestic": 1,
      "Catsize": 0,
      "Classification of Animal": 4
    },
    {
      "Hair": 0,
      "Feathers": 0,
      "Eggs": 1,
      "Milk": 0,
      "Airborne": 0,
      "Aquatic": 1,
      "Predator": 1,
      "Teeth": 1,
      "Backbone": 1,
      "Breathes": 0,
      "Venemous": 0,
      "Fins": 1,
      "Legs": 0,
      "Tails": 1,
      "Domestic": 0,
      "Catsize": 0,
      "Classification of Animal": 4
    },
    {
      "Hair": 1,
      "Feathers": 0,
      "Eggs": 0,
      "Milk": 1,
      "Airborne": 0,
      "Aquatic": 0,
      "Predator": 0,
      "Teeth": 1,
      "Backbone": 1,
      "Breathes": 1,
      "Venemous": 0,
      "Fins": 0,
      "Legs": 4,
      "Tails": 0,
      "Domestic": 1,
      "Catsize": 0,
      "Classification of Animal": 1
    },
    {
      "Hair": 1,
      "Feathers": 0,
      "Eggs": 0,
      "Milk": 1,
      "Airborne": 0,
      "Aquatic": 0,
      "Predator": 1,
      "Teeth": 1,
      "Backbone": 1,
      "Breathes": 1,
      "Venemous": 0,
      "Fins": 0,
      "Legs": 4,
      "Tails": 1,
      "Domestic": 0,
      "Catsize": 1,
      "Classification of Animal": 1
    },
    {
      "Hair": 0,
      "Feathers": 1,
      "Eggs": 1,
      "Milk": 0,
      "Airborne": 1,
      "Aquatic": 0,
      "Predator": 0,
      "Teeth": 0,
      "Backbone": 1,
      "Breathes": 1,
      "Venemous": 0,
      "Fins": 0,
      "Legs": 2,
      "Tails": 1,
      "Domestic": 1,
      "Catsize": 0,
      "Classification of Animal": 2
    },
    {
      "Hair": 0,
      "Feathers": 0,
      "Eggs": 1,
      "Milk": 0,
      "Airborne": 0,
      "Aquatic": 1,
      "Predator": 1,
      "Teeth": 1,
      "Backbone": 1,
      "Breathes": 0,
      "Venemous": 0,
      "Fins": 1,
      "Legs": 0,
      "Tails": 1,
      "Domestic": 0,
      "Catsize": 0,
      "Classification of Animal": 4
    },
    {
      "Hair": 0,
      "Feathers": 0,
      "Eggs": 1,
      "Milk": 0,
      "Airborne": 0,
      "Aquatic": 0,
      "Predator": 1,
      "Teeth": 0,
      "Backbone": 0,
      "Breathes": 0,
      "Venemous": 0,
      "Fins": 0,
      "Legs": 0,
      "Tails": 0,
      "Domestic": 0,
      "Catsize": 0,
      "Classification of Animal": 7
    },
    {
      "Hair": 0,
      "Feathers": 0,
      "Eggs": 1,
      "Milk": 0,
      "Airborne": 0,
      "Aquatic": 1,
      "Predator": 1,
      "Teeth": 0,
      "Backbone": 0,
      "Breathes": 0,
      "Venemous": 0,
      "Fins": 0,
      "Legs": 4,
      "Tails": 0,
      "Domestic": 0,
      "Catsize": 0,
      "Classification of Animal": 7
    },
    {
      "Hair": 0,
      "Feathers": 0,
      "Eggs": 1,
      "Milk": 0,
      "Airborne": 0,
      "Aquatic": 1,
      "Predator": 1,
      "Teeth": 0,
      "Backbone": 0,
      "Breathes": 0,
      "Venemous": 0,
      "Fins": 0,
      "Legs": 6,
      "Tails": 0,
      "Domestic": 0,
      "Catsize": 0,
      "Classification of Animal": 7
    },
    {
      "Hair": 0,
      "Feathers": 1,
      "Eggs": 1,
      "Milk": 0,
      "Airborne": 1,
      "Aquatic": 0,
      "Predator": 1,
      "Teeth": 0,
      "Backbone": 1,
      "Breathes": 1,
      "Venemous": 0,
      "Fins": 0,
      "Legs": 2,
      "Tails": 1,
      "Domestic": 0,
      "Catsize": 0,
      "Classification of Animal": 2
    },
    {
      "Hair": 1,
      "Feathers": 0,
      "Eggs": 0,
      "Milk": 1,
      "Airborne": 0,
      "Aquatic": 0,
      "Predator": 0,
      "Teeth": 1,
      "Backbone": 1,
      "Breathes": 1,
      "Venemous": 0,
      "Fins": 0,
      "Legs": 4,
      "Tails": 1,
      "Domestic": 0,
      "Catsize": 1,
      "Classification of Animal": 1
    },
    {
      "Hair": 0,
      "Feathers": 0,
      "Eggs": 1,
      "Milk": 0,
      "Airborne": 0,
      "Aquatic": 1,
      "Predator": 1,
      "Teeth": 1,
      "Backbone": 1,
      "Breathes": 0,
      "Venemous": 0,
      "Fins": 1,
      "Legs": 0,
      "Tails": 1,
      "Domestic": 0,
      "Catsize": 1,
      "Classification of Animal": 4
    },
    {
      "Hair": 0,
      "Feathers": 0,
      "Eggs": 0,
      "Milk": 1,
      "Airborne": 0,
      "Aquatic": 1,
      "Predator": 1,
      "Teeth": 1,
      "Backbone": 1,
      "Breathes": 1,
      "Venemous": 0,
      "Fins": 1,
      "Legs": 0,
      "Tails": 1,
      "Domestic": 0,
      "Catsize": 1,
      "Classification of Animal": 1
    },
    {
      "Hair": 0,
      "Feathers": 1,
      "Eggs": 1,
      "Milk": 0,
      "Airborne": 1,
      "Aquatic": 0,
      "Predator": 0,
      "Teeth": 0,
      "Backbone": 1,
      "Breathes": 1,
      "Venemous": 0,
      "Fins": 0,
      "Legs": 2,
      "Tails": 1,
      "Domestic": 1,
      "Catsize": 0,
      "Classification of Animal": 2
    },
    {
      "Hair": 0,
      "Feathers": 1,
      "Eggs": 1,
      "Milk": 0,
      "Airborne": 1,
      "Aquatic": 1,
      "Predator": 0,
      "Teeth": 0,
      "Backbone": 1,
      "Breathes": 1,
      "Venemous": 0,
      "Fins": 0,
      "Legs": 2,
      "Tails": 1,
      "Domestic": 0,
      "Catsize": 0,
      "Classification of Animal": 2
    },
    {
      "Hair": 1,
      "Feathers": 0,
      "Eggs": 0,
      "Milk": 1,
      "Airborne": 0,
      "Aquatic": 0,
      "Predator": 0,
      "Teeth": 1,
      "Backbone": 1,
      "Breathes": 1,
      "Venemous": 0,
      "Fins": 0,
      "Legs": 4,
      "Tails": 1,
      "Domestic": 0,
      "Catsize": 1,
      "Classification of Animal": 1
    },
    {
      "Hair": 0,
      "Feathers": 1,
      "Eggs": 1,
      "Milk": 0,
      "Airborne": 1,
      "Aquatic": 0,
      "Predator": 0,
      "Teeth": 0,
      "Backbone": 1,
      "Breathes": 1,
      "Venemous": 0,
      "Fins": 0,
      "Legs": 2,
      "Tails": 1,
      "Domestic": 0,
      "Catsize": 1,
      "Classification of Animal": 2
    },
    {
      "Hair": 0,
      "Feathers": 0,
      "Eggs": 1,
      "Milk": 0,
      "Airborne": 0,
      "Aquatic": 0,
      "Predator": 0,
      "Teeth": 0,
      "Backbone": 0,
      "Breathes": 1,
      "Venemous": 0,
      "Fins": 0,
      "Legs": 6,
      "Tails": 0,
      "Domestic": 0,
      "Catsize": 0,
      "Classification of Animal": 6
    },
    {
      "Hair": 0,
      "Feathers": 0,
      "Eggs": 1,
      "Milk": 0,
      "Airborne": 0,
      "Aquatic": 1,
      "Predator": 1,
      "Teeth": 1,
      "Backbone": 1,
      "Breathes": 1,
      "Venemous": 0,
      "Fins": 0,
      "Legs": 4,
      "Tails": 0,
      "Domestic": 0,
      "Catsize": 0,
      "Classification of Animal": 5
    },
    {
      "Hair": 0,
      "Feathers": 0,
      "Eggs": 1,
      "Milk": 0,
      "Airborne": 0,
      "Aquatic": 1,
      "Predator": 1,
      "Teeth": 1,
      "Backbone": 1,
      "Breathes": 1,
      "Venemous": 1,
      "Fins": 0,
      "Legs": 4,
      "Tails": 0,
      "Domestic": 0,
      "Catsize": 0,
      "Classification of Animal": 5
    },
    {
      "Hair": 1,
      "Feathers": 0,
      "Eggs": 0,
      "Milk": 1,
      "Airborne": 1,
      "Aquatic": 0,
      "Predator": 0,
      "Teeth": 1,
      "Backbone": 1,
      "Breathes": 1,
      "Venemous": 0,
      "Fins": 0,
      "Legs": 2,
      "Tails": 1,
      "Domestic": 0,
      "Catsize": 0,
      "Classification of Animal": 1
    },
    {
      "Hair": 1,
      "Feathers": 0,
      "Eggs": 0,
      "Milk": 1,
      "Airborne": 0,
      "Aquatic": 0,
      "Predator": 0,
      "Teeth": 1,
      "Backbone": 1,
      "Breathes": 1,
      "Venemous": 0,
      "Fins": 0,
      "Legs": 4,
      "Tails": 1,
      "Domestic": 0,
      "Catsize": 1,
      "Classification of Animal": 1
    },
    {
      "Hair": 1,
      "Feathers": 0,
      "Eggs": 0,
      "Milk": 1,
      "Airborne": 0,
      "Aquatic": 0,
      "Predator": 1,
      "Teeth": 1,
      "Backbone": 1,
      "Breathes": 1,
      "Venemous": 0,
      "Fins": 0,
      "Legs": 2,
      "Tails": 0,
      "Domestic": 1,
      "Catsize": 1,
      "Classification of Animal": 1
    },
    {
      "Hair": 0,
      "Feathers": 0,
      "Eggs": 1,
      "Milk": 0,
      "Airborne": 1,
      "Aquatic": 0,
      "Predator": 0,
      "Teeth": 0,
      "Backbone": 0,
      "Breathes": 1,
      "Venemous": 0,
      "Fins": 0,
      "Legs": 6,
      "Tails": 0,
      "Domestic": 0,
      "Catsize": 0,
      "Classification of Animal": 6
    },
    {
      "Hair": 1,
      "Feathers": 0,
      "Eggs": 0,
      "Milk": 1,
      "Airborne": 0,
      "Aquatic": 0,
      "Predator": 0,
      "Teeth": 1,
      "Backbone": 1,
      "Breathes": 1,
      "Venemous": 0,
      "Fins": 0,
      "Legs": 4,
      "Tails": 1,
      "Domestic": 1,
      "Catsize": 1,
      "Classification of Animal": 1
    },
    {
      "Hair": 1,
      "Feathers": 0,
      "Eggs": 0,
      "Milk": 1,
      "Airborne": 0,
      "Aquatic": 0,
      "Predator": 0,
      "Teeth": 1,
      "Backbone": 1,
      "Breathes": 1,
      "Venemous": 0,
      "Fins": 0,
      "Legs": 2,
      "Tails": 0,
      "Domestic": 0,
      "Catsize": 1,
      "Classification of Animal": 1
    },
    {
      "Hair": 0,
      "Feathers": 1,
      "Eggs": 1,
      "Milk": 0,
      "Airborne": 1,
      "Aquatic": 1,
      "Predator": 1,
      "Teeth": 0,
      "Backbone": 1,
      "Breathes": 1,
      "Venemous": 0,
      "Fins": 0,
      "Legs": 2,
      "Tails": 1,
      "Domestic": 0,
      "Catsize": 0,
      "Classification of Animal": 2
    },
    {
      "Hair": 0,
      "Feathers": 0,
      "Eggs": 1,
      "Milk": 0,
      "Airborne": 0,
      "Aquatic": 1,
      "Predator": 0,
      "Teeth": 1,
      "Backbone": 1,
      "Breathes": 0,
      "Venemous": 0,
      "Fins": 1,
      "Legs": 0,
      "Tails": 1,
      "Domestic": 0,
      "Catsize": 0,
      "Classification of Animal": 4
    },
    {
      "Hair": 1,
      "Feathers": 0,
      "Eggs": 0,
      "Milk": 1,
      "Airborne": 0,
      "Aquatic": 0,
      "Predator": 0,
      "Teeth": 1,
      "Backbone": 1,
      "Breathes": 1,
      "Venemous": 0,
      "Fins": 0,
      "Legs": 4,
      "Tails": 1,
      "Domestic": 1,
      "Catsize": 0,
      "Classification of Animal": 1
    },
    {
      "Hair": 1,
      "Feathers": 0,
      "Eggs": 0,
      "Milk": 1,
      "Airborne": 0,
      "Aquatic": 0,
      "Predator": 0,
      "Teeth": 1,
      "Backbone": 1,
      "Breathes": 1,
      "Venemous": 0,
      "Fins": 0,
      "Legs": 4,
      "Tails": 1,
      "Domestic": 0,
      "Catsize": 0,
      "Classification of Animal": 1
    },
    {
      "Hair": 0,
      "Feathers": 1,
      "Eggs": 1,
      "Milk": 0,
      "Airborne": 1,
      "Aquatic": 0,
      "Predator": 1,
      "Teeth": 0,
      "Backbone": 1,
      "Breathes": 1,
      "Venemous": 0,
      "Fins": 0,
      "Legs": 2,
      "Tails": 1,
      "Domestic": 0,
      "Catsize": 0,
      "Classification of Animal": 2
    },
    {
      "Hair": 0,
      "Feathers": 0,
      "Eggs": 1,
      "Milk": 0,
      "Airborne": 0,
      "Aquatic": 1,
      "Predator": 1,
      "Teeth": 1,
      "Backbone": 1,
      "Breathes": 0,
      "Venemous": 0,
      "Fins": 1,
      "Legs": 0,
      "Tails": 1,
      "Domestic": 0,
      "Catsize": 0,
      "Classification of Animal": 4
    },
    {
      "Hair": 1,
      "Feathers": 0,
      "Eggs": 1,
      "Milk": 0,
      "Airborne": 1,
      "Aquatic": 0,
      "Predator": 0,
      "Teeth": 0,
      "Backbone": 0,
      "Breathes": 1,
      "Venemous": 1,
      "Fins": 0,
      "Legs": 6,
      "Tails": 0,
      "Domestic": 1,
      "Catsize": 0,
      "Classification of Animal": 6
    },
    {
      "Hair": 1,
      "Feathers": 0,
      "Eggs": 1,
      "Milk": 0,
      "Airborne": 1,
      "Aquatic": 0,
      "Predator": 0,
      "Teeth": 0,
      "Backbone": 0,
      "Breathes": 1,
      "Venemous": 0,
      "Fins": 0,
      "Legs": 6,
      "Tails": 0,
      "Domestic": 0,
      "Catsize": 0,
      "Classification of Animal": 6
    },
    {
      "Hair": 0,
      "Feathers": 1,
      "Eggs": 1,
      "Milk": 0,
      "Airborne": 0,
      "Aquatic": 0,
      "Predator": 1,
      "Teeth": 0,
      "Backbone": 1,
      "Breathes": 1,
      "Venemous": 0,
      "Fins": 0,
      "Legs": 2,
      "Tails": 1,
      "Domestic": 0,
      "Catsize": 0,
      "Classification of Animal": 2
    },
    {
      "Hair": 0,
      "Feathers": 0,
      "Eggs": 1,
      "Milk": 0,
      "Airborne": 1,
      "Aquatic": 0,
      "Predator": 1,
      "Teeth": 0,
      "Backbone": 0,
      "Breathes": 1,
      "Venemous": 0,
      "Fins": 0,
      "Legs": 6,
      "Tails": 0,
      "Domestic": 0,
      "Catsize": 0,
      "Classification of Animal": 6
    },
    {
      "Hair": 0,
      "Feathers": 1,
      "Eggs": 1,
      "Milk": 0,
      "Airborne": 1,
      "Aquatic": 0,
      "Predator": 0,
      "Teeth": 0,
      "Backbone": 1,
      "Breathes": 1,
      "Venemous": 0,
      "Fins": 0,
      "Legs": 2,
      "Tails": 1,
      "Domestic": 0,
      "Catsize": 0,
      "Classification of Animal": 2
    },
    {
      "Hair": 1,
      "Feathers": 0,
      "Eggs": 0,
      "Milk": 1,
      "Airborne": 0,
      "Aquatic": 0,
      "Predator": 1,
      "Teeth": 1,
      "Backbone": 1,
      "Breathes": 1,
      "Venemous": 0,
      "Fins": 0,
      "Legs": 4,
      "Tails": 1,
      "Domestic": 0,
      "Catsize": 1,
      "Classification of Animal": 1
    },
    {
      "Hair": 1,
      "Feathers": 0,
      "Eggs": 0,
      "Milk": 1,
      "Airborne": 0,
      "Aquatic": 0,
      "Predator": 1,
      "Teeth": 1,
      "Backbone": 1,
      "Breathes": 1,
      "Venemous": 0,
      "Fins": 0,
      "Legs": 4,
      "Tails": 1,
      "Domestic": 0,
      "Catsize": 1,
      "Classification of Animal": 1
    },
    {
      "Hair": 0,
      "Feathers": 0,
      "Eggs": 1,
      "Milk": 0,
      "Airborne": 0,
      "Aquatic": 1,
      "Predator": 1,
      "Teeth": 0,
      "Backbone": 0,
      "Breathes": 0,
      "Venemous": 0,
      "Fins": 0,
      "Legs": 6,
      "Tails": 0,
      "Domestic": 0,
      "Catsize": 0,
      "Classification of Animal": 7
    },
    {
      "Hair": 1,
      "Feathers": 0,
      "Eggs": 0,
      "Milk": 1,
      "Airborne": 0,
      "Aquatic": 0,
      "Predator": 1,
      "Teeth": 1,
      "Backbone": 1,
      "Breathes": 1,
      "Venemous": 0,
      "Fins": 0,
      "Legs": 4,
      "Tails": 1,
      "Domestic": 0,
      "Catsize": 1,
      "Classification of Animal": 1
    },
    {
      "Hair": 1,
      "Feathers": 0,
      "Eggs": 0,
      "Milk": 1,
      "Airborne": 0,
      "Aquatic": 1,
      "Predator": 1,
      "Teeth": 1,
      "Backbone": 1,
      "Breathes": 1,
      "Venemous": 0,
      "Fins": 0,
      "Legs": 4,
      "Tails": 1,
      "Domestic": 0,
      "Catsize": 1,
      "Classification of Animal": 1
    },
    {
      "Hair": 1,
      "Feathers": 0,
      "Eggs": 0,
      "Milk": 1,
      "Airborne": 0,
      "Aquatic": 0,
      "Predator": 1,
      "Teeth": 1,
      "Backbone": 1,
      "Breathes": 1,
      "Venemous": 0,
      "Fins": 0,
      "Legs": 4,
      "Tails": 1,
      "Domestic": 0,
      "Catsize": 0,
      "Classification of Animal": 1
    },
    {
      "Hair": 1,
      "Feathers": 0,
      "Eggs": 0,
      "Milk": 1,
      "Airborne": 0,
      "Aquatic": 0,
      "Predator": 1,
      "Teeth": 1,
      "Backbone": 1,
      "Breathes": 1,
      "Venemous": 0,
      "Fins": 0,
      "Legs": 4,
      "Tails": 1,
      "Domestic": 0,
      "Catsize": 1,
      "Classification of Animal": 1
    },
    {
      "Hair": 1,
      "Feathers": 0,
      "Eggs": 1,
      "Milk": 0,
      "Airborne": 1,
      "Aquatic": 0,
      "Predator": 0,
      "Teeth": 0,
      "Backbone": 0,
      "Breathes": 1,
      "Venemous": 0,
      "Fins": 0,
      "Legs": 6,
      "Tails": 0,
      "Domestic": 0,
      "Catsize": 0,
      "Classification of Animal": 6
    },
    {
      "Hair": 0,
      "Feathers": 0,
      "Eggs": 1,
      "Milk": 0,
      "Airborne": 0,
      "Aquatic": 1,
      "Predator": 1,
      "Teeth": 1,
      "Backbone": 1,
      "Breathes": 1,
      "Venemous": 0,
      "Fins": 0,
      "Legs": 4,
      "Tails": 1,
      "Domestic": 0,
      "Catsize": 0,
      "Classification of Animal": 5
    },
    {
      "Hair": 0,
      "Feathers": 0,
      "Eggs": 1,
      "Milk": 0,
      "Airborne": 0,
      "Aquatic": 1,
      "Predator": 1,
      "Teeth": 0,
      "Backbone": 0,
      "Breathes": 0,
      "Venemous": 0,
      "Fins": 0,
      "Legs": 8,
      "Tails": 0,
      "Domestic": 0,
      "Catsize": 1,
      "Classification of Animal": 7
    },
    {
      "Hair": 1,
      "Feathers": 0,
      "Eggs": 0,
      "Milk": 1,
      "Airborne": 0,
      "Aquatic": 0,
      "Predator": 1,
      "Teeth": 1,
      "Backbone": 1,
      "Breathes": 1,
      "Venemous": 0,
      "Fins": 0,
      "Legs": 4,
      "Tails": 1,
      "Domestic": 0,
      "Catsize": 0,
      "Classification of Animal": 1
    },
    {
      "Hair": 1,
      "Feathers": 0,
      "Eggs": 0,
      "Milk": 1,
      "Airborne": 0,
      "Aquatic": 0,
      "Predator": 0,
      "Teeth": 1,
      "Backbone": 1,
      "Breathes": 1,
      "Venemous": 0,
      "Fins": 0,
      "Legs": 4,
      "Tails": 1,
      "Domestic": 0,
      "Catsize": 1,
      "Classification of Animal": 1
    },
    {
      "Hair": 0,
      "Feathers": 1,
      "Eggs": 1,
      "Milk": 0,
      "Airborne": 0,
      "Aquatic": 0,
      "Predator": 0,
      "Teeth": 0,
      "Backbone": 1,
      "Breathes": 1,
      "Venemous": 0,
      "Fins": 0,
      "Legs": 2,
      "Tails": 1,
      "Domestic": 0,
      "Catsize": 1,
      "Classification of Animal": 2
    },
    {
      "Hair": 0,
      "Feathers": 1,
      "Eggs": 1,
      "Milk": 0,
      "Airborne": 1,
      "Aquatic": 0,
      "Predator": 0,
      "Teeth": 0,
      "Backbone": 1,
      "Breathes": 1,
      "Venemous": 0,
      "Fins": 0,
      "Legs": 2,
      "Tails": 1,
      "Domestic": 1,
      "Catsize": 0,
      "Classification of Animal": 2
    },
    {
      "Hair": 0,
      "Feathers": 1,
      "Eggs": 1,
      "Milk": 0,
      "Airborne": 0,
      "Aquatic": 1,
      "Predator": 1,
      "Teeth": 0,
      "Backbone": 1,
      "Breathes": 1,
      "Venemous": 0,
      "Fins": 0,
      "Legs": 2,
      "Tails": 1,
      "Domestic": 0,
      "Catsize": 1,
      "Classification of Animal": 2
    },
    {
      "Hair": 0,
      "Feathers": 1,
      "Eggs": 1,
      "Milk": 0,
      "Airborne": 1,
      "Aquatic": 0,
      "Predator": 0,
      "Teeth": 0,
      "Backbone": 1,
      "Breathes": 1,
      "Venemous": 0,
      "Fins": 0,
      "Legs": 2,
      "Tails": 1,
      "Domestic": 0,
      "Catsize": 0,
      "Classification of Animal": 2
    },
    {
      "Hair": 0,
      "Feathers": 0,
      "Eggs": 1,
      "Milk": 0,
      "Airborne": 0,
      "Aquatic": 1,
      "Predator": 1,
      "Teeth": 1,
      "Backbone": 1,
      "Breathes": 0,
      "Venemous": 0,
      "Fins": 1,
      "Legs": 0,
      "Tails": 1,
      "Domestic": 0,
      "Catsize": 1,
      "Classification of Animal": 4
    },
    {
      "Hair": 0,
      "Feathers": 0,
      "Eggs": 1,
      "Milk": 0,
      "Airborne": 0,
      "Aquatic": 1,
      "Predator": 1,
      "Teeth": 1,
      "Backbone": 1,
      "Breathes": 0,
      "Venemous": 0,
      "Fins": 1,
      "Legs": 0,
      "Tails": 1,
      "Domestic": 0,
      "Catsize": 0,
      "Classification of Animal": 4
    },
    {
      "Hair": 0,
      "Feathers": 0,
      "Eggs": 1,
      "Milk": 0,
      "Airborne": 0,
      "Aquatic": 0,
      "Predator": 1,
      "Teeth": 1,
      "Backbone": 1,
      "Breathes": 1,
      "Venemous": 1,
      "Fins": 0,
      "Legs": 0,
      "Tails": 1,
      "Domestic": 0,
      "Catsize": 0,
      "Classification of Animal": 3
    },
    {
      "Hair": 1,
      "Feathers": 0,
      "Eggs": 1,
      "Milk": 1,
      "Airborne": 0,
      "Aquatic": 1,
      "Predator": 1,
      "Teeth": 0,
      "Backbone": 1,
      "Breathes": 1,
      "Venemous": 0,
      "Fins": 0,
      "Legs": 4,
      "Tails": 1,
      "Domestic": 0,
      "Catsize": 1,
      "Classification of Animal": 1
    },
    {
      "Hair": 1,
      "Feathers": 0,
      "Eggs": 0,
      "Milk": 1,
      "Airborne": 0,
      "Aquatic": 0,
      "Predator": 1,
      "Teeth": 1,
      "Backbone": 1,
      "Breathes": 1,
      "Venemous": 0,
      "Fins": 0,
      "Legs": 4,
      "Tails": 1,
      "Domestic": 0,
      "Catsize": 1,
      "Classification of Animal": 1
    },
    {
      "Hair": 1,
      "Feathers": 0,
      "Eggs": 0,
      "Milk": 1,
      "Airborne": 0,
      "Aquatic": 0,
      "Predator": 0,
      "Teeth": 1,
      "Backbone": 1,
      "Breathes": 1,
      "Venemous": 0,
      "Fins": 0,
      "Legs": 4,
      "Tails": 1,
      "Domestic": 1,
      "Catsize": 1,
      "Classification of Animal": 1
    },
    {
      "Hair": 0,
      "Feathers": 0,
      "Eggs": 0,
      "Milk": 1,
      "Airborne": 0,
      "Aquatic": 1,
      "Predator": 1,
      "Teeth": 1,
      "Backbone": 1,
      "Breathes": 1,
      "Venemous": 0,
      "Fins": 1,
      "Legs": 0,
      "Tails": 1,
      "Domestic": 0,
      "Catsize": 1,
      "Classification of Animal": 1
    },
    {
      "Hair": 1,
      "Feathers": 0,
      "Eggs": 0,
      "Milk": 1,
      "Airborne": 0,
      "Aquatic": 0,
      "Predator": 1,
      "Teeth": 1,
      "Backbone": 1,
      "Breathes": 1,
      "Venemous": 0,
      "Fins": 0,
      "Legs": 4,
      "Tails": 1,
      "Domestic": 0,
      "Catsize": 1,
      "Classification of Animal": 1
    },
    {
      "Hair": 1,
      "Feathers": 0,
      "Eggs": 0,
      "Milk": 1,
      "Airborne": 0,
      "Aquatic": 0,
      "Predator": 1,
      "Teeth": 1,
      "Backbone": 1,
      "Breathes": 1,
      "Venemous": 0,
      "Fins": 0,
      "Legs": 4,
      "Tails": 1,
      "Domestic": 1,
      "Catsize": 1,
      "Classification of Animal": 1
    },
    {
      "Hair": 1,
      "Feathers": 0,
      "Eggs": 0,
      "Milk": 1,
      "Airborne": 0,
      "Aquatic": 0,
      "Predator": 1,
      "Teeth": 1,
      "Backbone": 1,
      "Breathes": 1,
      "Venemous": 0,
      "Fins": 0,
      "Legs": 4,
      "Tails": 1,
      "Domestic": 0,
      "Catsize": 1,
      "Classification of Animal": 1
    },
    {
      "Hair": 1,
      "Feathers": 0,
      "Eggs": 0,
      "Milk": 1,
      "Airborne": 0,
      "Aquatic": 0,
      "Predator": 0,
      "Teeth": 1,
      "Backbone": 1,
      "Breathes": 1,
      "Venemous": 0,
      "Fins": 0,
      "Legs": 4,
      "Tails": 1,
      "Domestic": 1,
      "Catsize": 1,
      "Classification of Animal": 1
    },
    {
      "Hair": 0,
      "Feathers": 1,
      "Eggs": 1,
      "Milk": 0,
      "Airborne": 0,
      "Aquatic": 0,
      "Predator": 1,
      "Teeth": 0,
      "Backbone": 1,
      "Breathes": 1,
      "Venemous": 0,
      "Fins": 0,
      "Legs": 2,
      "Tails": 1,
      "Domestic": 0,
      "Catsize": 1,
      "Classification of Animal": 2
    },
    {
      "Hair": 0,
      "Feathers": 0,
      "Eggs": 0,
      "Milk": 0,
      "Airborne": 0,
      "Aquatic": 0,
      "Predator": 1,
      "Teeth": 0,
      "Backbone": 0,
      "Breathes": 1,
      "Venemous": 1,
      "Fins": 0,
      "Legs": 8,
      "Tails": 1,
      "Domestic": 0,
      "Catsize": 0,
      "Classification of Animal": 7
    },
    {
      "Hair": 0,
      "Feathers": 0,
      "Eggs": 1,
      "Milk": 0,
      "Airborne": 0,
      "Aquatic": 1,
      "Predator": 0,
      "Teeth": 1,
      "Backbone": 1,
      "Breathes": 0,
      "Venemous": 0,
      "Fins": 1,
      "Legs": 0,
      "Tails": 1,
      "Domestic": 0,
      "Catsize": 0,
      "Classification of Animal": 4
    },
    {
      "Hair": 1,
      "Feathers": 0,
      "Eggs": 0,
      "Milk": 1,
      "Airborne": 0,
      "Aquatic": 1,
      "Predator": 1,
      "Teeth": 1,
      "Backbone": 1,
      "Breathes": 1,
      "Venemous": 0,
      "Fins": 1,
      "Legs": 0,
      "Tails": 0,
      "Domestic": 0,
      "Catsize": 1,
      "Classification of Animal": 1
    },
    {
      "Hair": 1,
      "Feathers": 0,
      "Eggs": 0,
      "Milk": 1,
      "Airborne": 0,
      "Aquatic": 1,
      "Predator": 1,
      "Teeth": 1,
      "Backbone": 1,
      "Breathes": 1,
      "Venemous": 0,
      "Fins": 1,
      "Legs": 2,
      "Tails": 1,
      "Domestic": 0,
      "Catsize": 1,
      "Classification of Animal": 1
    },
    {
      "Hair": 0,
      "Feathers": 0,
      "Eggs": 0,
      "Milk": 0,
      "Airborne": 0,
      "Aquatic": 1,
      "Predator": 1,
      "Teeth": 1,
      "Backbone": 1,
      "Breathes": 0,
      "Venemous": 1,
      "Fins": 0,
      "Legs": 0,
      "Tails": 1,
      "Domestic": 0,
      "Catsize": 0,
      "Classification of Animal": 3
    },
    {
      "Hair": 0,
      "Feathers": 0,
      "Eggs": 1,
      "Milk": 0,
      "Airborne": 0,
      "Aquatic": 1,
      "Predator": 1,
      "Teeth": 0,
      "Backbone": 0,
      "Breathes": 0,
      "Venemous": 1,
      "Fins": 0,
      "Legs": 0,
      "Tails": 0,
      "Domestic": 0,
      "Catsize": 0,
      "Classification of Animal": 7
    },
    {
      "Hair": 0,
      "Feathers": 1,
      "Eggs": 1,
      "Milk": 0,
      "Airborne": 1,
      "Aquatic": 1,
      "Predator": 1,
      "Teeth": 0,
      "Backbone": 1,
      "Breathes": 1,
      "Venemous": 0,
      "Fins": 0,
      "Legs": 2,
      "Tails": 1,
      "Domestic": 0,
      "Catsize": 0,
      "Classification of Animal": 2
    },
    {
      "Hair": 0,
      "Feathers": 1,
      "Eggs": 1,
      "Milk": 0,
      "Airborne": 1,
      "Aquatic": 1,
      "Predator": 1,
      "Teeth": 0,
      "Backbone": 1,
      "Breathes": 1,
      "Venemous": 0,
      "Fins": 0,
      "Legs": 2,
      "Tails": 1,
      "Domestic": 0,
      "Catsize": 0,
      "Classification of Animal": 2
    },
    {
      "Hair": 0,
      "Feathers": 0,
      "Eggs": 1,
      "Milk": 0,
      "Airborne": 0,
      "Aquatic": 0,
      "Predator": 1,
      "Teeth": 1,
      "Backbone": 1,
      "Breathes": 1,
      "Venemous": 0,
      "Fins": 0,
      "Legs": 0,
      "Tails": 1,
      "Domestic": 0,
      "Catsize": 0,
      "Classification of Animal": 3
    },
    {
      "Hair": 0,
      "Feathers": 0,
      "Eggs": 1,
      "Milk": 0,
      "Airborne": 0,
      "Aquatic": 0,
      "Predator": 0,
      "Teeth": 0,
      "Backbone": 0,
      "Breathes": 1,
      "Venemous": 0,
      "Fins": 0,
      "Legs": 0,
      "Tails": 0,
      "Domestic": 0,
      "Catsize": 0,
      "Classification of Animal": 7
    },
    {
      "Hair": 0,
      "Feathers": 0,
      "Eggs": 1,
      "Milk": 0,
      "Airborne": 0,
      "Aquatic": 1,
      "Predator": 0,
      "Teeth": 1,
      "Backbone": 1,
      "Breathes": 0,
      "Venemous": 0,
      "Fins": 1,
      "Legs": 0,
      "Tails": 1,
      "Domestic": 0,
      "Catsize": 0,
      "Classification of Animal": 4
    },
    {
      "Hair": 0,
      "Feathers": 1,
      "Eggs": 1,
      "Milk": 0,
      "Airborne": 1,
      "Aquatic": 0,
      "Predator": 0,
      "Teeth": 0,
      "Backbone": 1,
      "Breathes": 1,
      "Venemous": 0,
      "Fins": 0,
      "Legs": 2,
      "Tails": 1,
      "Domestic": 0,
      "Catsize": 0,
      "Classification of Animal": 2
    },
    {
      "Hair": 1,
      "Feathers": 0,
      "Eggs": 0,
      "Milk": 1,
      "Airborne": 0,
      "Aquatic": 0,
      "Predator": 0,
      "Teeth": 1,
      "Backbone": 1,
      "Breathes": 1,
      "Venemous": 0,
      "Fins": 0,
      "Legs": 2,
      "Tails": 1,
      "Domestic": 0,
      "Catsize": 0,
      "Classification of Animal": 1
    },
    {
      "Hair": 0,
      "Feathers": 0,
      "Eggs": 1,
      "Milk": 0,
      "Airborne": 0,
      "Aquatic": 1,
      "Predator": 1,
      "Teeth": 0,
      "Backbone": 0,
      "Breathes": 0,
      "Venemous": 0,
      "Fins": 0,
      "Legs": 5,
      "Tails": 0,
      "Domestic": 0,
      "Catsize": 0,
      "Classification of Animal": 7
    },
    {
      "Hair": 0,
      "Feathers": 0,
      "Eggs": 1,
      "Milk": 0,
      "Airborne": 0,
      "Aquatic": 1,
      "Predator": 1,
      "Teeth": 1,
      "Backbone": 1,
      "Breathes": 0,
      "Venemous": 1,
      "Fins": 1,
      "Legs": 0,
      "Tails": 1,
      "Domestic": 0,
      "Catsize": 1,
      "Classification of Animal": 4
    },
    {
      "Hair": 0,
      "Feathers": 1,
      "Eggs": 1,
      "Milk": 0,
      "Airborne": 1,
      "Aquatic": 1,
      "Predator": 0,
      "Teeth": 0,
      "Backbone": 1,
      "Breathes": 1,
      "Venemous": 0,
      "Fins": 0,
      "Legs": 2,
      "Tails": 1,
      "Domestic": 0,
      "Catsize": 1,
      "Classification of Animal": 2
    },
    {
      "Hair": 0,
      "Feathers": 0,
      "Eggs": 1,
      "Milk": 0,
      "Airborne": 0,
      "Aquatic": 0,
      "Predator": 0,
      "Teeth": 0,
      "Backbone": 0,
      "Breathes": 1,
      "Venemous": 0,
      "Fins": 0,
      "Legs": 6,
      "Tails": 0,
      "Domestic": 0,
      "Catsize": 0,
      "Classification of Animal": 6
    },
    {
      "Hair": 0,
      "Feathers": 0,
      "Eggs": 1,
      "Milk": 0,
      "Airborne": 0,
      "Aquatic": 1,
      "Predator": 0,
      "Teeth": 1,
      "Backbone": 1,
      "Breathes": 1,
      "Venemous": 0,
      "Fins": 0,
      "Legs": 4,
      "Tails": 0,
      "Domestic": 0,
      "Catsize": 0,
      "Classification of Animal": 5
    },
    {
      "Hair": 0,
      "Feathers": 0,
      "Eggs": 1,
      "Milk": 0,
      "Airborne": 0,
      "Aquatic": 0,
      "Predator": 0,
      "Teeth": 0,
      "Backbone": 1,
      "Breathes": 1,
      "Venemous": 0,
      "Fins": 0,
      "Legs": 4,
      "Tails": 1,
      "Domestic": 0,
      "Catsize": 1,
      "Classification of Animal": 3
    },
    {
      "Hair": 0,
      "Feathers": 0,
      "Eggs": 1,
      "Milk": 0,
      "Airborne": 0,
      "Aquatic": 0,
      "Predator": 1,
      "Teeth": 1,
      "Backbone": 1,
      "Breathes": 1,
      "Venemous": 0,
      "Fins": 0,
      "Legs": 4,
      "Tails": 1,
      "Domestic": 0,
      "Catsize": 0,
      "Classification of Animal": 3
    },
    {
      "Hair": 0,
      "Feathers": 0,
      "Eggs": 1,
      "Milk": 0,
      "Airborne": 0,
      "Aquatic": 1,
      "Predator": 1,
      "Teeth": 1,
      "Backbone": 1,
      "Breathes": 0,
      "Venemous": 0,
      "Fins": 1,
      "Legs": 0,
      "Tails": 1,
      "Domestic": 0,
      "Catsize": 1,
      "Classification of Animal": 4
    },
    {
      "Hair": 1,
      "Feathers": 0,
      "Eggs": 0,
      "Milk": 1,
      "Airborne": 1,
      "Aquatic": 0,
      "Predator": 0,
      "Teeth": 1,
      "Backbone": 1,
      "Breathes": 1,
      "Venemous": 0,
      "Fins": 0,
      "Legs": 2,
      "Tails": 1,
      "Domestic": 0,
      "Catsize": 0,
      "Classification of Animal": 1
    },
    {
      "Hair": 1,
      "Feathers": 0,
      "Eggs": 0,
      "Milk": 1,
      "Airborne": 0,
      "Aquatic": 0,
      "Predator": 0,
      "Teeth": 1,
      "Backbone": 1,
      "Breathes": 1,
      "Venemous": 0,
      "Fins": 0,
      "Legs": 4,
      "Tails": 1,
      "Domestic": 0,
      "Catsize": 0,
      "Classification of Animal": 1
    },
    {
      "Hair": 0,
      "Feathers": 1,
      "Eggs": 1,
      "Milk": 0,
      "Airborne": 1,
      "Aquatic": 0,
      "Predator": 1,
      "Teeth": 0,
      "Backbone": 1,
      "Breathes": 1,
      "Venemous": 0,
      "Fins": 0,
      "Legs": 2,
      "Tails": 1,
      "Domestic": 0,
      "Catsize": 1,
      "Classification of Animal": 2
    },
    {
      "Hair": 1,
      "Feathers": 0,
      "Eggs": 0,
      "Milk": 1,
      "Airborne": 0,
      "Aquatic": 0,
      "Predator": 0,
      "Teeth": 1,
      "Backbone": 1,
      "Breathes": 1,
      "Venemous": 0,
      "Fins": 0,
      "Legs": 2,
      "Tails": 1,
      "Domestic": 0,
      "Catsize": 1,
      "Classification of Animal": 1
    },
    {
      "Hair": 1,
      "Feathers": 0,
      "Eggs": 1,
      "Milk": 0,
      "Airborne": 1,
      "Aquatic": 0,
      "Predator": 0,
      "Teeth": 0,
      "Backbone": 0,
      "Breathes": 1,
      "Venemous": 1,
      "Fins": 0,
      "Legs": 6,
      "Tails": 0,
      "Domestic": 0,
      "Catsize": 0,
      "Classification of Animal": 6
    },
    {
      "Hair": 1,
      "Feathers": 0,
      "Eggs": 0,
      "Milk": 1,
      "Airborne": 0,
      "Aquatic": 0,
      "Predator": 1,
      "Teeth": 1,
      "Backbone": 1,
      "Breathes": 1,
      "Venemous": 0,
      "Fins": 0,
      "Legs": 4,
      "Tails": 1,
      "Domestic": 0,
      "Catsize": 1,
      "Classification of Animal": 1
    },
    {
      "Hair": 0,
      "Feathers": 0,
      "Eggs": 1,
      "Milk": 0,
      "Airborne": 0,
      "Aquatic": 0,
      "Predator": 0,
      "Teeth": 0,
      "Backbone": 0,
      "Breathes": 1,
      "Venemous": 0,
      "Fins": 0,
      "Legs": 0,
      "Tails": 0,
      "Domestic": 0,
      "Catsize": 0,
      "Classification of Animal": 7
    },
    {
      "Hair": 0,
      "Feathers": 1,
      "Eggs": 1,
      "Milk": 0,
      "Airborne": 1,
      "Aquatic": 0,
      "Predator": 0,
      "Teeth": 0,
      "Backbone": 1,
      "Breathes": 1,
      "Venemous": 0,
      "Fins": 0,
      "Legs": 2,
      "Tails": 1,
      "Domestic": 0,
      "Catsize": 0,
      "Classification of Animal": 2
    }
  ]

  export default conjuntoEntrenamiento3;